import fs from 'node:fs/promises';
import path from 'node:path';
import type { FileSpec, FixtureSpec, PresetName } from '../types.js';
import { presetNames } from '../presets/registry.js';
import { FixtureForgeError } from './errors.js';
import { parseSimpleYaml, toSimpleYaml } from './yaml.js';
import { normalizeSpecPath } from './path-safety.js';

export const defaultSpec: FixtureSpec = {
  name: 'demo-fixture',
  seed: 'demo-seed',
  presets: ['node-cli'],
  files: [
    { path: 'notes/custom.txt', content: 'Generated by fixtureforge.\n' },
    { path: 'data/random.txt', lines: 4 }
  ]
};

export async function writeDefaultSpec(destination: string): Promise<void> {
  const ext = path.extname(destination).toLowerCase();
  const body = ext === '.yaml' || ext === '.yml' ? toSimpleYaml(defaultSpec as Record<string, unknown>) : `${JSON.stringify(defaultSpec, null, 2)}\n`;
  await fs.mkdir(path.dirname(path.resolve(destination)), { recursive: true });
  await fs.writeFile(destination, body, 'utf8');
}

export async function loadSpec(specPath: string): Promise<FixtureSpec> {
  const text = await fs.readFile(specPath, 'utf8');
  const ext = path.extname(specPath).toLowerCase();
  const data = ext === '.yaml' || ext === '.yml' ? parseSimpleYaml(text) : JSON.parse(text) as unknown;
  return validateSpec(data);
}

export function validateSpec(data: unknown): FixtureSpec {
  if (!data || typeof data !== 'object' || Array.isArray(data)) throw new FixtureForgeError('E_SPEC', 'Spec must be an object.');
  const raw = data as FixtureSpec;
  const spec: FixtureSpec = {
    name: typeof raw.name === 'string' ? raw.name : 'fixture',
    seed: raw.seed ?? 'fixtureforge',
    presets: validatePresets(raw.presets),
    directories: validatePaths(raw.directories, 'directories'),
    files: validateFiles(raw.files),
    symlinks: Array.isArray(raw.symlinks) ? raw.symlinks.map((link) => {
      if (!link || typeof link !== 'object' || typeof link.path !== 'string' || typeof link.target !== 'string') {
        throw new FixtureForgeError('E_SPEC_SYMLINK', 'Symlink entries require path and target strings.');
      }
      return { path: normalizeSpecPath(link.path), target: link.target };
    }) : [],
    warnings: Array.isArray(raw.warnings) ? raw.warnings.map(String) : []
  };
  return spec;
}

function validatePresets(value: FixtureSpec['presets']): PresetName[] {
  if (value === undefined) return [];
  if (!Array.isArray(value)) throw new FixtureForgeError('E_SPEC_PRESETS', 'presets must be an array.');
  return value.map((item) => {
    if (!presetNames.includes(item as PresetName)) throw new FixtureForgeError('E_SPEC_PRESET_UNKNOWN', `Unknown preset: ${String(item)}`);
    return item as PresetName;
  });
}

function validatePaths(value: unknown, label: string): string[] {
  if (value === undefined) return [];
  if (!Array.isArray(value)) throw new FixtureForgeError('E_SPEC_PATHS', `${label} must be an array.`);
  return value.map((item) => normalizeSpecPath(String(item)));
}

function validateFiles(value: unknown): FileSpec[] {
  if (value === undefined) return [];
  if (!Array.isArray(value)) throw new FixtureForgeError('E_SPEC_FILES', 'files must be an array.');
  return value.map((item) => {
    if (!item || typeof item !== 'object' || typeof (item as FileSpec).path !== 'string') {
      throw new FixtureForgeError('E_SPEC_FILE', 'File entries require a path string.');
    }
    const file = item as FileSpec;
    return {
      ...file,
      path: normalizeSpecPath(file.path),
      bytes: file.bytes === undefined ? undefined : Math.max(0, Number(file.bytes)),
      lines: file.lines === undefined ? undefined : Math.max(0, Number(file.lines))
    };
  });
}
